language: node_js

node_js:
- 10.10.0

branches:
  only:
  - develop

before_install:
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install hexo-cli -g

install:
- npm install

before_script:
- git config --global user.name 'Inouelab Admin'
- git config --global user.email 'inouelab.calc@gmail.com'

script:
- hexo generate

after_success:
- git clone --depth 1 --branch master git@github.com:inouelab-waseda/inouelab-waseda.github.io.git .deploy
- cd .deploy
- cp -rf ../public/* .
- git add .
- git commit -m "Site updated"
- git push origin master

